### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ufinal** [lateautumn233/android_kernel_oneplus_sm8250#2]
Do you have oneplus8t kernel for android 13 with nethunter support?

**Comment by lateautumn233** [comment]
I can give it a try

**Comment by ufinal** [comment]
perfect..i can test it

**Comment by lateautumn233** [comment]
> perfect..i can test it

I didn't test it 
https://qiuqiu233.top/anykernel-NetHunter.zip

**Comment by ufinal** [comment]
i am on Crdroid 9.1(Android 13),after flashing phone didnt boot.Shell i test it on OOS13?

**Comment by lateautumn233** [comment]
> i am on Crdroid 9.1(Android 13),after flashing phone didnt boot.Shell i test it on OOS13?

Is stuck in the first screen?

**Comment by ufinal** [comment]
even no screen, animation ect..,just black screen.

**Comment by lateautumn233** [comment]
> even no screen, animation ect..,just black screen.

I updated the file 
https://qiuqiu233.top/anykernel-NetHunter.zip
![IMG_20230201_153659](https://user-images.githubusercontent.com/63851402/215980203-3b0abc48-c4f0-4fd3-932d-bff14d0bfee8.jpg)

**Comment by ufinal** [comment]
![10 51 41](https://user-images.githubusercontent.com/17437624/215984037-8c1dc830-abe4-4d1f-b972-d42cdd1510a5.jpg)

just that screen then black screen.

**Comment by ufinal** [comment]
https://forum.xda-developers.com/t/kernel-custom-rom-kreig-kernel-v-1-2-7-4-19-271-oneplus-8-series-android-13-1-30-2023.4535997/page-3

shell i share your kernel here?because my phone might have problem.Kreig-Kernel on that topic didnt work on my phone either but  other people say it worked.maybe your kernel would work for other people

**Comment by ufinal** [comment]
ok let me install Nameless-AOSP_kebab-13

**Comment by lateautumn233** [comment]
> https://forum.xda-developers.com/t/kernel-custom-rom-kreig-kernel-v-1-2-7-4-19-271-oneplus-8-series-android-13-1-30-2023.4535997/page-3
> 
> shell i share your kernel here?because my phone might have problem.Kreig-Kernel on that topic didnt work on my phone either but other people say it worked.maybe your kernel would work for other people

Did you disable the avb?

**Comment by ufinal** [comment]
oh i think no,let me try it

**Comment by ufinal** [comment]
![Adsız](https://user-images.githubusercontent.com/17437624/216000151-edd6352b-5877-43fa-9942-be7ea4787ddc.jpg)
flashed vbmeta.img and empty vbmeta.img but no luck yet....trying...

**Comment by ufinal** [comment]
seems avb is ok
![12 35 01](https://user-images.githubusercontent.com/17437624/216007994-1a2f9357-ad90-43e4-8efe-88b2d0261d30.jpg)

**Comment by lateautumn233** [comment]
> seems avb is ok ![12 35 01](https://user-images.githubusercontent.com/17437624/216007994-1a2f9357-ad90-43e4-8efe-88b2d0261d30.jpg)

Maybe it's a crdroid problem

**Comment by ufinal** [comment]
![13 41 02](https://user-images.githubusercontent.com/17437624/216022094-0557c4fd-9f2b-4d71-bea6-04fe9e5ff5c4.jpg)

flashing seems ok but it doesnt boot

**Comment by lateautumn233** [comment]
> ![13 41 02](https://user-images.githubusercontent.com/17437624/216022094-0557c4fd-9f2b-4d71-bea6-04fe9e5ff5c4.jpg)
> 
> flashing seems ok but it doesnt boot

nameless?

**Comment by ufinal** [comment]
crdroid

**Comment by lateautumn233** [comment]
> crdroid

Try nameless, I don't understand why

**Comment by ufinal** [comment]
ok finally worked on nameless,flashed kernel without problem.tested internal wifi and it works but when you press  "stop wlan0 monitor mode"  it gives that error: you cant open wifi without resetting.
![00 08 34](https://user-images.githubusercontent.com/17437624/216165295-5f92124d-4043-4e2a-909f-ffb20f8ae85a.jpg)


and external wifi...i have 2 adaptors, one has chipset  ralink rt3572 which was always working fine , the other has chipset  realtek 8812bu which is hard to run.

**Comment by ufinal** [comment]
my both adaptors dont work.

**Comment by ufinal** [comment]
maybe you should use  CONFIG_MODULE_FORCE_UNLOAD=y in your defconfig

**Comment by lateautumn233** [comment]
[rt3572](https://github.com/lateautumn233/android_kernel_oneplus_sm8250/blob/8ffbafb25767702c856796f806d90195ed5793de/drivers/net/wireless/ralink/rt2x00/Kconfig#L161) 
![Screenshot_2023-02-02-09-23-07-476_bin mt plus](https://user-images.githubusercontent.com/63851402/216207881-b59ef23a-c052-4840-97ca-a98a990d2c83.jpg)

realtek 8812bu Configuration not found

**Comment by lateautumn233** [comment]
I think I found it 
https://github.com/fastoe/RTL8812BU

**Comment by lateautumn233** [comment]
> [rt3572](https://github.com/lateautumn233/android_kernel_oneplus_sm8250/blob/8ffbafb25767702c856796f806d90195ed5793de/drivers/net/wireless/ralink/rt2x00/Kconfig#L161) ![Screenshot_2023-02-02-09-23-07-476_bin mt plus](https://user-images.githubusercontent.com/63851402/216207881-b59ef23a-c052-4840-97ca-a98a990d2c83.jpg)
> 
> realtek 8812bu Configuration not found

I think I may have forgotten it

**Comment by lateautumn233** [comment]
https://alist.buer.app/d/linux-deploy/anykernel-NetHunter.zip

**Comment by lateautumn233** [comment]
realtek 8812bu
https://alist.buer.app/d/linux-deploy/strip88x2bu.ko

**Comment by ufinal** [comment]
great now ralink rt3572 is working fine.(both monitor mode and packet injection)
internal wifi monitor mode works but problem continues...after  i stop wlan0 monitor mode ,i cant open wifi..i have to reset phone then wifi works again.

**Comment by ufinal** [comment]
realtek 8812bu..
also there is one more driver here 
https://github.com/cilynx/rtl88x2bu
with the one you found
https://github.com/fastoe/RTL8812BU

**Comment by ufinal** [comment]
my kernel directory  /lib/modules/   is emty,i dont know how to install strip88x2bu.ko

**Comment by ufinal** [comment]
for internal wifi using  CONFIG_MODULE_FORCE_UNLOAD=y in your defconfig   is good idea

**Comment by lateautumn233** [comment]
> my kernel directory /lib/modules/ is emty,i dont know how to install strip88x2bu.ko

insmod strip88x2bu.ko

**Comment by ufinal** [comment]
result 
![10 04 05](https://user-images.githubusercontent.com/17437624/216256046-1353bbf7-3a0f-46b0-a769-34ea48f5c7bb.jpg)

**Comment by lateautumn233** [comment]
> result ![10 04 05](https://user-images.githubusercontent.com/17437624/216256046-1353bbf7-3a0f-46b0-a769-34ea48f5c7bb.jpg)

dmesg?

**Comment by ufinal** [comment]
dmesg
[dmesg.txt](https://github.com/lateautumn233/android_kernel_oneplus_sm8250/files/10566221/dmesg.txt)

**Comment by lateautumn233** [comment]
> dmesg [dmesg.txt](https://github.com/lateautumn233/android_kernel_oneplus_sm8250/files/10566221/dmesg.txt)

You need to resmod before sending out the log

**Comment by ufinal** [comment]
well i didnt understand resmod

**Comment by ufinal** [comment]
re insmod?

**Comment by lateautumn233** [comment]
> re insmod?

Yes, I use translation software

**Comment by ufinal** [comment]
insmod strip88x2bu.ko
dmesg

[dmesg2.txt](https://github.com/lateautumn233/android_kernel_oneplus_sm8250/files/10566446/dmesg2.txt)

**Comment by lateautumn233** [comment]
> insmod strip88x2bu.ko dmesg
> 
> [dmesg2.txt](https://github.com/lateautumn233/android_kernel_oneplus_sm8250/files/10566446/dmesg2.txt)

I don't see any logs about 88x2bu
try
```
/system/bin/insmod strip88x2bu.ko
```

**Comment by ufinal** [comment]
/system/bin/  is read-only  (EROFS)
can it be because of that?

**Comment by ufinal** [comment]
![11 17 45](https://user-images.githubusercontent.com/17437624/216270307-3dee1695-5e9e-4d9d-995c-188dc0da2fe3.jpg)

**Comment by ufinal** [comment]
busy with this...
https://forum.xda-developers.com/t/closed-the-real-makerw-ro2rw-v1-0-by-lebigmac-read-only-2-read-write-partition-converter-erofs-rw-ext4-rw-f2fs-rw.4536821/

**Comment by lateautumn233** [comment]
I updated the link 
https://alist.buer.app/d/linux-deploy/anykernel-NetHunter.zip
[Source](https://github.com/lateautumn233/android_kernel_oneplus_sm8250/commits/nethuntermod)

**Comment by ufinal** [comment]
ok good news about realtek 8812bu;
its now visible in airmon-ng but putting in monitor mode fails.
a little more work is needed.

![13 46 56](https://user-images.githubusercontent.com/17437624/216304875-212e2c08-2e62-4d39-a09a-082429dab2f3.jpg)

**Comment by ufinal** [comment]
ralink rt3572 works perfect. (monitor mode and packet injection)
internal wifi works fine (monitor mode )  but after stoping monitor mode you need to reset phone to get wifi work

**Comment by ufinal** [comment]
great news
finally realtek 8812bu worked!

sudo ifconfig wlan0 down
sudo airmon-ng check kill
sudo iwconfig wlan0 mode monitor

**Comment by lateautumn233** [comment]
> great news finally realtek 8812bu worked!
> 
> sudo ifconfig wlan0 down sudo airmon-ng check kill sudo iwconfig wlan0 mode monitor

What happened?

**Comment by ufinal** [comment]
realtek 8812bu is now working (monitor mode and injection)

**Comment by lateautumn233** [comment]
> realtek 8812bu is now working (monitor mode and injection)

How did you fix it ?

**Comment by ufinal** [comment]
> > realtek 8812bu is now working (monitor mode and injection)
> 
> How did you fix it ?
sudo ifconfig wlan0 down
sudo airmon-ng check kill
sudo iwconfig wlan0 mode monitor

then 
besside-ng wlan0
or
wifite -i wlan0

wlan0 is realtek 8812bu  at the moment

**Comment by ufinal** [comment]
by the way,i have no internet in nethunter,do you have any idea?i cant ping,i cant apt update...
i had the same problem when i was on OOS 13 but when i was on crdroid (android 13) i didnt have such a problem.
![16 14 06](https://user-images.githubusercontent.com/17437624/216335904-0898bdb7-b20f-4d17-a951-ac9345a25474.jpg)

**Comment by lateautumn233** [comment]
Try Linuxdeploy?

**Comment by ufinal** [comment]
groupadd -g 3003 aid_inet && usermod -G nogroup -g aid_inet _apt
    echo 'APT::Sandbox::User "root";' > /etc/apt/apt.conf.d/01-android-nosandbox

this solved apt update problem

**Comment by ufinal** [comment]
so now we have  just a small problem.internal wifi doesnt work until  resetting phone after stoping monitor mode.

**Comment by ufinal** [comment]
thank you very much for your great work.i added you to favorite.i will find you when android 14 is out :)

**Comment by lateautumn233** [comment]
> thank you very much for your great work.i added you to favorite.i will find you when android 14 is out :)

Thanks
